// Pre-renders every public page to static HTML after `vite build`.
//
// Why: the site is a single-page app, so `dist/index.html` is an empty shell
// until JavaScript runs. Google renders JavaScript (slowly, in a second
// pass); Bing, the AI crawlers (GPTBot, ClaudeBot, PerplexityBot) and the
// link-preview bots of WhatsApp, Facebook and Instagram mostly do not. This
// script gives each public URL a real HTML file with the page's content, its
// own <title>, description, canonical link, Open Graph card and JSON-LD, so
// all of them see the page as a visitor would.
//
// How: Vite loads the app in Node (src/entry-server.jsx), React renders each
// route from src/seo/pages.js to a string, and the result is written to
// `dist/<route>/index.html` (the home page to `dist/index.html`). The untouched
// shell is kept as `dist/spa.html`, which vercel.json (and public/_redirects)
// fall back to for every URL that has no pre-rendered file: the portal, the
// redirects, unknown paths. Hosting serves static files before rewrites, so a
// pre-rendered page always wins over the shell.
//
// The browser keeps mounting with createRoot(): React replaces the
// pre-rendered markup with the live app on load. The content is identical, so
// nothing visibly changes; only the crawlers and preview bots benefit.
//
// sitemap.xml is generated from the same page list, so a new committee, album
// or page is listed the moment it is added there.
import fs from 'node:fs/promises'
import path from 'node:path'
import { createServer } from 'vite'

const root = process.cwd()
const dist = path.join(root, 'dist')

const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

// `<` never appears literally inside a script data block, or a stray "</script>"
// in a description could end it early.
const jsonLdScript = (obj) =>
  `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, '\\u003c')}</script>`

// Rewrite the `content` attribute of one <meta name|property="..."> tag,
// whatever its attribute order or line breaks.
function setMeta(html, attr, name, value) {
  const re = new RegExp(`<meta\\s+[^>]*${attr}="${name}"[^>]*>`, 'i')
  const m = html.match(re)
  if (!m) throw new Error(`index.html has no <meta ${attr}="${name}">`)
  const tag = m[0].replace(/content="[^"]*"/i, `content="${escapeHtml(value)}"`)
  return html.replace(m[0], tag)
}

function buildHtml(template, page, appHtml) {
  let html = template
  html = html.replace(/<title>[^<]*<\/title>/i, `<title>${escapeHtml(page.fullTitle)}</title>`)
  html = setMeta(html, 'name', 'description', page.description)
  html = html.replace(
    /<link\s+rel="canonical"[^>]*>/i,
    `<link rel="canonical" href="${escapeHtml(page.url)}" />`,
  )
  html = setMeta(html, 'property', 'og:title', page.fullTitle)
  html = setMeta(html, 'property', 'og:description', page.description)
  html = setMeta(html, 'property', 'og:url', page.url)
  html = setMeta(html, 'property', 'og:image', page.image)
  html = setMeta(html, 'property', 'og:image:alt', page.imageAlt)
  html = setMeta(html, 'name', 'twitter:title', page.fullTitle)
  html = setMeta(html, 'name', 'twitter:description', page.description)
  html = setMeta(html, 'name', 'twitter:image', page.image)

  // The shell's generic organisation block is replaced by the page's own set
  // (the home page carries the full organisation record).
  html = html.replace(/\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/i, '')
  html = html.replace('</head>', `    ${page.jsonLd.map(jsonLdScript).join('\n    ')}\n  </head>`)

  const marker = '<div id="root"></div>'
  if (!html.includes(marker)) throw new Error('index.html has no empty #root')
  html = html.replace(marker, `<div id="root">${appHtml}</div>`)
  return html
}

function sitemapXml(pages) {
  const rows = pages.map(
    (p) =>
      `  <url><loc>${escapeHtml(p.url)}</loc><changefreq>${p.changefreq}</changefreq><priority>${p.priority.toFixed(1)}</priority></url>`,
  )
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/prerender.mjs from src/seo/pages.js at build time. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${rows.join('\n')}\n</urlset>\n`
}

// llms.txt (https://llmstxt.org): a plain-text map of the site for AI
// assistants, generated from the same page list so it never goes stale.
function llmsTxt(pages) {
  const line = (p) => `- [${p.title || 'Home'}](${p.url}): ${p.description}`
  const top = pages.filter((p) => !p.path.startsWith('/committees/') && !p.path.startsWith('/gallery/'))
  const committees = pages.filter((p) => p.path.startsWith('/committees/'))
  const albums = pages.filter((p) => p.path.startsWith('/gallery/'))
  return [
    "# AUSSS, Ain Shams University Students' Scientific Society",
    '',
    "> The student-run scientific society of the Faculty of Medicine, Ain Shams University, Cairo, Egypt, founded in 1971. Motto: Life Savers, Change Makers. AUSSS is an autonomous affiliate of IFMSA-Egypt, the Egyptian member of the International Federation of Medical Students' Associations (IFMSA). It runs six IFMSA standing committees (SCOPE, SCORE, SCOME, SCORP, SCOPH, SCORA) and four support divisions (PSD, PNSD, CBSD, RSD): medical research, public health campaigns, medical education, human rights, sexual and reproductive health, and international clinical and research exchanges.",
    '',
    'Also referred to as the Ain Shams University Student Scientific Society, AUSSS Ain Shams, or IFMSA Ain Shams (it is the IFMSA society of Ain Shams University). Official site: https://ausss-ainshams.org (every page below is served as full HTML). Contact: ausss.secgen@gmail.com (Secretary General). Instagram, Facebook and TikTok: @ausss_ainshams.',
    '',
    '## Pages',
    '',
    ...top.map(line),
    '',
    '## Committees and divisions',
    '',
    ...committees.map(line),
    '',
    '## Photo albums',
    '',
    ...albums.map(line),
    '',
    '## Notes',
    '',
    '- The members portal at /portal is sign-in only and not for indexing.',
    '- Membership is open to students of the Faculty of Medicine, Ain Shams University; see /join.',
    '',
  ].join('\n')
}

async function main() {
  const template = await fs.readFile(path.join(dist, 'index.html'), 'utf8')
  await fs.writeFile(path.join(dist, 'spa.html'), template)

  const vite = await createServer({
    root,
    mode: 'production',
    logLevel: 'error',
    server: { middlewareMode: true, hmr: false },
    appType: 'custom',
    // React Router's Node entry is CommonJS, which Vite's SSR loader cannot
    // evaluate; point both packages at their ESM files and let Vite bundle
    // them so the app's router and StaticRouter are one instance.
    resolve: {
      alias: [
        { find: /^react-router-dom$/, replacement: path.join(root, 'node_modules/react-router-dom/dist/index.mjs') },
        { find: /^react-router\/dom$/, replacement: path.join(root, 'node_modules/react-router/dist/development/dom-export.mjs') },
        { find: /^react-router$/, replacement: path.join(root, 'node_modules/react-router/dist/development/index.mjs') },
      ],
    },
    ssr: { noExternal: ['react-router', 'react-router-dom'] },
  })
  try {
    const { render } = await vite.ssrLoadModule('/src/entry-server.jsx')
    const { publicPages } = await vite.ssrLoadModule('/src/seo/pages.js')
    const pages = publicPages()

    const seen = new Set()
    for (const page of pages) {
      if (seen.has(page.path)) throw new Error(`duplicate page path ${page.path}`)
      seen.add(page.path)
      const appHtml = await render(page.path)
      if (!appHtml.includes('<main')) {
        throw new Error(`${page.path} rendered without a <main>: is the route registered in App.jsx?`)
      }
      const out =
        page.path === '/'
          ? path.join(dist, 'index.html')
          : path.join(dist, ...page.path.slice(1).split('/'), 'index.html')
      await fs.mkdir(path.dirname(out), { recursive: true })
      await fs.writeFile(out, buildHtml(template, page, appHtml))
    }
    await fs.writeFile(path.join(dist, 'sitemap.xml'), sitemapXml(pages))
    await fs.writeFile(path.join(dist, 'llms.txt'), llmsTxt(pages))
    console.log(`prerender: ${pages.length} pages written; sitemap.xml and llms.txt list ${pages.length} URLs`)
  } finally {
    await vite.close()
  }
}

main().catch((err) => {
  console.error('prerender failed:', err)
  process.exit(1)
})
