// Pre-renders every public page to static HTML after `vite build`.
//
// Why: the site is a single-page app, so `dist/index.html` is an empty shell
// until JavaScript runs. Google renders JavaScript (slowly, in a second
// pass); Bing, the AI crawlers (GPTBot, ClaudeBot, PerplexityBot) and the
// link-preview bots of WhatsApp, Facebook and Instagram mostly do not. This
// script gives each public URL a real HTML file with the page's content, its
// own <title>, description, canonical link, Open Graph card and JSON-LD, so
// all of them see the page as a visitor would.
//
// How: Vite loads the app in Node (src/entry-server.jsx), React renders each
// route from src/seo/pages.js to a string, and the result is written to
// `dist/<route>/index.html` (the home page to `dist/index.html`). The untouched
// shell is kept as `dist/spa.html`, which vercel.json falls back to for every
// URL that has no pre-rendered file: the portal, the redirects, unknown paths.
// Vercel serves static files before rewrites, so a pre-rendered page always
// wins over the shell.
//
// The browser keeps mounting with createRoot(): React replaces the
// pre-rendered markup with the live app on load. The content is identical, so
// nothing visibly changes; only the crawlers and preview bots benefit.
//
// sitemap.xml is generated from the same page list, so a new committee, album
// or page is listed the moment it is added there.
//
// Three small files are written next to it: page-hashes.json and
// indexnow-urls.json (which pages changed since the live build, for
// scripts/indexnow.mjs) and .well-known/security.txt.
import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { createServer } from 'vite'

const root = process.cwd()
const dist = path.join(root, 'dist')

const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

// `<` never appears literally inside a script data block, or a stray "</script>"
// in a description could end it early.
const jsonLdScript = (obj) =>
  `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, '\\u003c')}</script>`

// Rewrite the `content` attribute of one <meta name|property="..."> tag,
// whatever its attribute order or line breaks.
function setMeta(html, attr, name, value) {
  const re = new RegExp(`<meta\\s+[^>]*${attr}="${name}"[^>]*>`, 'i')
  const m = html.match(re)
  if (!m) throw new Error(`index.html has no <meta ${attr}="${name}">`)
  const tag = m[0].replace(/content="[^"]*"/i, `content="${escapeHtml(value)}"`)
  return html.replace(m[0], tag)
}

function buildHtml(template, page, appHtml) {
  let html = template
  html = html.replace(/<title>[^<]*<\/title>/i, `<title>${escapeHtml(page.fullTitle)}</title>`)
  html = setMeta(html, 'name', 'description', page.description)
  html = html.replace(
    /<link\s+rel="canonical"[^>]*>/i,
    `<link rel="canonical" href="${escapeHtml(page.url)}" />`,
  )
  html = setMeta(html, 'property', 'og:title', page.fullTitle)
  html = setMeta(html, 'property', 'og:description', page.description)
  html = setMeta(html, 'property', 'og:url', page.url)
  html = setMeta(html, 'property', 'og:image', page.image)
  html = setMeta(html, 'property', 'og:image:alt', page.imageAlt)
  html = setMeta(html, 'name', 'twitter:title', page.fullTitle)
  html = setMeta(html, 'name', 'twitter:description', page.description)
  html = setMeta(html, 'name', 'twitter:image', page.image)

  // The shell's generic organisation block is replaced by the page's own set
  // (the home page carries the full organisation record).
  html = html.replace(/\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/i, '')
  html = html.replace('</head>', `    ${page.jsonLd.map(jsonLdScript).join('\n    ')}\n  </head>`)

  // The hero logo is the largest paint on the home page only, so only that
  // page asks for it early (anywhere else the preload would go unused).
  if (page.path === '/') {
    html = html.replace(
      '</head>',
      '    <link rel="preload" as="image" href="/assets/brand/ausss-vertical-white.png" fetchpriority="high" />\n  </head>',
    )
  }

  const marker = '<div id="root"></div>'
  if (!html.includes(marker)) throw new Error('index.html has no empty #root')
  html = html.replace(marker, `<div id="root">${appHtml}</div>`)
  return html
}

function sitemapXml(pages) {
  const rows = pages.map(
    (p) =>
      `  <url><loc>${escapeHtml(p.url)}</loc><changefreq>${p.changefreq}</changefreq><priority>${p.priority.toFixed(1)}</priority></url>`,
  )
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/prerender.mjs from src/seo/pages.js at build time. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${rows.join('\n')}\n</urlset>\n`
}

// llms.txt (https://llmstxt.org): a plain-text map of the site for AI
// assistants, generated from the same page list so it never goes stale.
function llmsTxt(pages, contactEmail) {
  const line = (p) => `- [${p.title || 'Home'}](${p.url}): ${p.description}`
  const top = pages.filter((p) => !p.path.startsWith('/committees/') && !p.path.startsWith('/gallery/'))
  const committees = pages.filter((p) => p.path.startsWith('/committees/'))
  const albums = pages.filter((p) => p.path.startsWith('/gallery/'))
  return [
    "# AUSSS, Ain Shams University Students' Scientific Society",
    '',
    "> The student-run scientific society of the Faculty of Medicine, Ain Shams University, Cairo, Egypt, founded in 1971. Motto: Life Savers, Change Makers. AUSSS is an autonomous affiliate of IFMSA-Egypt, the Egyptian member of the International Federation of Medical Students' Associations (IFMSA). It runs six IFMSA standing committees (SCOPE, SCORE, SCOME, SCORP, SCOPH, SCORA) and four support divisions (PSD, PNSD, CBSD, RSD): medical research, public health campaigns, medical education, human rights, sexual and reproductive health, and international clinical and research exchanges.",
    '',
    `Also referred to as the Ain Shams University Student Scientific Society, AUSSS Ain Shams, or IFMSA Ain Shams (it is the IFMSA society of Ain Shams University). Official site: https://ausss-ainshams.org (every page below is served as full HTML). Contact: ${contactEmail} (Secretary General). Instagram, Facebook and TikTok: @ausss_ainshams.`,
    '',
    '## Pages',
    '',
    ...top.map(line),
    '',
    '## Committees and divisions',
    '',
    ...committees.map(line),
    '',
    '## Photo albums',
    '',
    ...albums.map(line),
    '',
    '## Notes',
    '',
    '- The members portal at /portal is sign-in only and not for indexing.',
    '- Membership is open to students of the Faculty of Medicine, Ain Shams University; see /join.',
    '',
  ].join('\n')
}

// What a reader sees of one page: its title, description and pre-rendered
// body. The rest of the <head> is left out because its script and stylesheet
// names change on every build, which would mark every page as changed.
function contentHash(html) {
  const title = html.match(/<title>[^<]*<\/title>/i)?.[0] || ''
  const description = html.match(/<meta\s+name="description"[^>]*>/i)?.[0] || ''
  const start = html.indexOf('<div id="root">')
  const body = (start === -1 ? html : html.slice(start)).replace(/<script[\s\S]*?<\/script>/gi, '')
  return createHash('sha256').update(title).update(description).update(body).digest('hex')
}

// The URLs whose content differs from the build that is live now, which
// published its own hashes as /page-hashes.json. Every URL counts as changed
// when the live site has no such file yet; none does when the site cannot be
// reached, so a build without network never floods IndexNow on the next run.
async function changedSinceLive(siteUrl, hashes) {
  let live
  try {
    const res = await fetch(`${siteUrl}/page-hashes.json`, { signal: AbortSignal.timeout(10000) })
    live = res.ok ? await res.json().catch(() => ({})) : {}
  } catch (err) {
    console.warn(`prerender: could not read the live page hashes (${err.message}); no IndexNow list this build`)
    return []
  }
  if (!live || typeof live !== 'object' || Array.isArray(live)) live = {}
  return Object.keys(hashes).filter((url) => live[url] !== hashes[url])
}

// RFC 9116: where to report a security problem. Expires is required and must
// stay in the future, so it is stamped a year ahead on every build.
function securityTxt(siteUrl) {
  const expires = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000)
  expires.setUTCHours(0, 0, 0, 0)
  return [
    'Contact: mailto:aussswebsite@gmail.com',
    `Expires: ${expires.toISOString()}`,
    'Preferred-Languages: en, ar',
    `Canonical: ${siteUrl}/.well-known/security.txt`,
    '',
  ].join('\n')
}

// The gallery lives in the database (portal editor); fetch it once so the album
// pages and their share cards are pre-rendered with real photos. Without the
// Supabase env vars (a local build without .env.local) the gallery index is
// rendered empty and no album pages exist; the browser fills it in at runtime.
async function loadAlbums(vite) {
  const gallery = await vite.ssrLoadModule('/src/lib/gallery.js')
  try {
    const live = await gallery.fetchGalleryAlbums()
    console.log(`prerender: ${live.length} albums from the database`)
    return live
  } catch (err) {
    console.warn(`prerender: could not fetch the gallery (${err.message}); no album pages this build`)
    return []
  }
}

// Same for the magazine shelf (src/lib/magazine.js): /magazine is pre-rendered
// with the latest edition and its cover page in the share card.
async function loadIssues(vite) {
  const magazine = await vite.ssrLoadModule('/src/lib/magazine.js')
  try {
    const live = await magazine.fetchMagazineIssues()
    console.log('prerender: ' + live.length + ' magazine editions from the database')
    return live
  } catch (err) {
    console.warn('prerender: could not fetch the magazine (' + err.message + '); the shelf renders empty this build')
    return []
  }
}

// And the published exchange stories (src/lib/exchangeStories.js) for the
// exchange pages.
async function loadStories(vite) {
  const mod = await vite.ssrLoadModule('/src/lib/exchangeStories.js')
  try {
    const live = await mod.fetchExchangeStories()
    console.log('prerender: ' + live.length + ' published exchange stories from the database')
    return live
  } catch (err) {
    console.warn('prerender: could not fetch the exchange stories (' + err.message + '); none this build')
    return []
  }
}

// And who holds each officer and board position this term (src/lib/people.js),
// so the board, the committee cards and the contact page are pre-rendered with
// the names and photos from the portal. An empty list renders society.js.
async function loadPeople(vite) {
  const mod = await vite.ssrLoadModule('/src/lib/people.js')
  try {
    const live = await mod.fetchPeople()
    console.log('prerender: ' + live.length + ' position holders from the database')
    return live
  } catch (err) {
    console.warn('prerender: could not fetch the position holders (' + err.message + '); the pages use society.js this build')
    return []
  }
}

// And the documents published from the portal's content editor
// (src/lib/content.js): the FAQ and, later, the other edited pages. With
// none, every block renders the copy that ships in the code.
async function loadContent(vite) {
  const mod = await vite.ssrLoadModule('/src/lib/content.js')
  try {
    const live = await mod.fetchContentBlocks()
    console.log('prerender: ' + Object.keys(live).length + ' published content blocks from the database')
    return live
  } catch (err) {
    console.warn('prerender: could not fetch the edited content (' + err.message + '); the pages use the shipped copy this build')
    return {}
  }
}

async function main() {
  const template = await fs.readFile(path.join(dist, 'index.html'), 'utf8')
  await fs.writeFile(path.join(dist, 'spa.html'), template)

  const vite = await createServer({
    root,
    mode: 'production',
    logLevel: 'error',
    server: { middlewareMode: true, hmr: false },
    appType: 'custom',
    // React Router's Node entry is CommonJS, which Vite's SSR loader cannot
    // evaluate; point both packages at their ESM files and let Vite bundle
    // them so the app's router and StaticRouter are one instance.
    resolve: {
      alias: [
        { find: /^react-router-dom$/, replacement: path.join(root, 'node_modules/react-router-dom/dist/index.mjs') },
        { find: /^react-router\/dom$/, replacement: path.join(root, 'node_modules/react-router/dist/development/dom-export.mjs') },
        { find: /^react-router$/, replacement: path.join(root, 'node_modules/react-router/dist/development/index.mjs') },
      ],
    },
    ssr: { noExternal: ['react-router', 'react-router-dom'] },
  })
  try {
    const { render } = await vite.ssrLoadModule('/src/entry-server.jsx')
    const { publicPages, SITE_URL } = await vite.ssrLoadModule('/src/seo/pages.js')
    const { society } = await vite.ssrLoadModule('/src/data/society.js')
    const albums = await loadAlbums(vite)
    const issues = await loadIssues(vite)
    const stories = await loadStories(vite)
    const people = await loadPeople(vite)
    const content = await loadContent(vite)
    const pages = publicPages(albums, issues, content)

    const seen = new Set()
    const hashes = {}
    for (const page of pages) {
      if (seen.has(page.path)) throw new Error(`duplicate page path ${page.path}`)
      seen.add(page.path)
      const appHtml = await render(page.path, albums, issues, stories, people, content)
      if (!appHtml.includes('<main')) {
        throw new Error(`${page.path} rendered without a <main>: is the route registered in App.jsx?`)
      }
      const out =
        page.path === '/'
          ? path.join(dist, 'index.html')
          : path.join(dist, ...page.path.slice(1).split('/'), 'index.html')
      await fs.mkdir(path.dirname(out), { recursive: true })
      const html = buildHtml(template, page, appHtml)
      await fs.writeFile(out, html)
      hashes[page.url] = contentHash(html)
    }
    await fs.writeFile(path.join(dist, 'sitemap.xml'), sitemapXml(pages))
    await fs.writeFile(path.join(dist, 'llms.txt'), llmsTxt(pages, society.contactEmail))
    const changed = await changedSinceLive(SITE_URL, hashes)
    await fs.writeFile(path.join(dist, 'page-hashes.json'), JSON.stringify(hashes))
    await fs.writeFile(path.join(dist, 'indexnow-urls.json'), JSON.stringify(changed))
    await fs.mkdir(path.join(dist, '.well-known'), { recursive: true })
    await fs.writeFile(path.join(dist, '.well-known', 'security.txt'), securityTxt(SITE_URL))
    console.log(`prerender: ${pages.length} pages written; sitemap.xml and llms.txt list ${pages.length} URLs; ${changed.length} changed since the live build`)
  } finally {
    await vite.close()
  }
}

main().catch((err) => {
  console.error('prerender failed:', err)
  process.exit(1)
})
