-- gen: generated by scripts/db/gen-reference-data.mjs on 2026-09-13T10:11:17.612Z
-- gen: do not edit by hand; edit src/data/society.js and run `npm run db:gen-reference`.
-- gen: idempotent upserts keyed on terms.label / committees.slug / positions.key.
-- Terms -------------------------------------------------------------------
-- is_current is not overwritten on conflict: the EB rolls the term over via
-- public.set_current_term(); re-running this migration must not undo that.
insert into public.terms (label, starts_on, ends_on, is_current)
values ('2025-26', '2025-09-01', '2026-08-31', false)
on conflict (label) do update set
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on;

insert into public.terms (label, starts_on, ends_on, is_current)
values ('2026-27', '2026-09-01', '2027-08-31', true)
on conflict (label) do update set
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on;

-- Committees --------------------------------------------------------------
-- page stays {} until Phase 2; content lives in src/data/society.js for now.
insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('scope', 'Professional Exchange', 'SCOPE', 'standing', '#0181c1', '/assets/logos/SCOPE.png', 0, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('score', 'Research Exchange', 'SCORE', 'standing', '#2e4a9c', '/assets/logos/SCORE.png', 1, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('scome', 'Medical Education', 'SCOME', 'standing', '#100016', '/assets/logos/SCOME.png', 2, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('scorp', 'Human Rights & Peace', 'SCORP', 'standing', '#5f903f', '/assets/logos/SCORP.png', 3, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('scoph', 'Public Health', 'SCOPH', 'standing', '#f47d3b', '/assets/logos/SCOPH.png', 4, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('scora', 'Sexual & Reproductive Health & Rights', 'SCORA', 'standing', '#bd202a', '/assets/logos/SCORA.png', 5, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('psd', 'Projects Support Division', 'PSD', 'division', '#107A72', '/assets/logos/PSD.png', 6, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('pnsd', 'Publications Support Division', 'PNSD', 'division', '#9F1547', '/assets/logos/PNSD.png', 7, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('cbsd', 'Capacity Building Support Division', 'CBSD', 'division', '#1E1E17', '/assets/logos/CBSD.png', 8, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

insert into public.committees (slug, name, abbr, kind, color, logo, sort, page)
values ('rsd', 'Research Support Division', 'RSD', 'division', '#F7B826', '/assets/logos/RSD.png', 9, '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  abbr = excluded.abbr,
  kind = excluded.kind,
  color = excluded.color,
  logo = excluded.logo,
  sort = excluded.sort;

-- Positions ---------------------------------------------------------------
insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scope.leo-out', (select id from public.committees where slug = 'scope'), 'Local Exchange Officer (LEO-Out)', 'LEO-Out', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scope.leo-in', (select id from public.committees where slug = 'scope'), 'Local Exchange Officer (LEO-In)', 'LEO-In', 'officer', 1, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scope.assistant', (select id from public.committees where slug = 'scope'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scope.member', (select id from public.committees where slug = 'scope'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('score.lore', (select id from public.committees where slug = 'score'), 'Local Officer on Research Exchange', 'LORE', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('score.assistant', (select id from public.committees where slug = 'score'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('score.member', (select id from public.committees where slug = 'score'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scome.lome', (select id from public.committees where slug = 'scome'), 'Local Officer on Medical Education', 'LOME', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scome.assistant', (select id from public.committees where slug = 'scome'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scome.member', (select id from public.committees where slug = 'scome'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scorp.lorp', (select id from public.committees where slug = 'scorp'), 'Local Officer on Human Rights & Peace', 'LORP', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scorp.assistant', (select id from public.committees where slug = 'scorp'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scorp.member', (select id from public.committees where slug = 'scorp'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scoph.lpo', (select id from public.committees where slug = 'scoph'), 'Local Public Health Officer', 'LPO', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scoph.assistant', (select id from public.committees where slug = 'scoph'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scoph.member', (select id from public.committees where slug = 'scoph'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scora.lora', (select id from public.committees where slug = 'scora'), 'Local Officer on SRHR & HIV/AIDS', 'LORA', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scora.assistant', (select id from public.committees where slug = 'scora'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('scora.member', (select id from public.committees where slug = 'scora'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('psd.psdd', (select id from public.committees where slug = 'psd'), 'Division Director', 'PSDD', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('psd.assistant', (select id from public.committees where slug = 'psd'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('psd.member', (select id from public.committees where slug = 'psd'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('pnsd.pnsdd', (select id from public.committees where slug = 'pnsd'), 'Division Director', 'PNSDD', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('pnsd.assistant', (select id from public.committees where slug = 'pnsd'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('pnsd.member', (select id from public.committees where slug = 'pnsd'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('cbsd.cbsdd', (select id from public.committees where slug = 'cbsd'), 'Division Director', 'CBSDD', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('cbsd.assistant', (select id from public.committees where slug = 'cbsd'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('cbsd.member', (select id from public.committees where slug = 'cbsd'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('rsd.rsdd', (select id from public.committees where slug = 'rsd'), 'Division Director', 'RSDD', 'officer', 0, true)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('rsd.assistant', (select id from public.committees where slug = 'rsd'), 'Assistant', null, 'assistant', 10, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('rsd.member', (select id from public.committees where slug = 'rsd'), 'Member', null, 'member', 20, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('eb.president', null, 'President', 'President', 'eb', 0, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('eb.vp-internal', null, 'Vice President, Internal Affairs', 'VPI', 'eb', 1, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('eb.vp-external', null, 'Vice President, External Affairs', 'VPE', 'eb', 2, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('eb.secretary-general', null, 'Secretary General', 'SecGen', 'eb', 3, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

insert into public.positions (key, committee_id, title, short_title, level, sort, can_assign_tasks)
values ('society.webmaster', null, 'Webmaster', 'Webmaster', 'webmaster', 0, false)
on conflict (key) do update set
  committee_id = excluded.committee_id,
  title = excluded.title,
  short_title = excluded.short_title,
  level = excluded.level,
  sort = excluded.sort,
  can_assign_tasks = excluded.can_assign_tasks;

-- Invites for the current term (2026-27) ----------------------------------
-- Role mailboxes from society.js (already public in this repo). Unique on
-- (email_normalized, position_id, term_id), so re-running is a no-op.
insert into public.invites (email, position_id, term_id)
select 'leolore.out.ausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scope.leo-out' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'leolore.in.ausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scope.leo-in' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'loreausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'score.lore' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'ausss.lome@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scome.lome' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'lorpausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scorp.lorp' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'lpoausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scoph.lpo' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'loraausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'scora.lora' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'psddausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'psd.psdd' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'aussspnsdd@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'pnsd.pnsdd' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'aussscbsdd@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'cbsd.cbsdd' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'rsddausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'rsd.rsdd' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'the.president.ausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'eb.president' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'vpi.ausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'eb.vp-internal' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'vpe.ausss@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'eb.vp-external' and t.label = '2026-27'
on conflict do nothing;

insert into public.invites (email, position_id, term_id)
select 'ausss.secgen@gmail.com', p.id, t.id
from public.positions p, public.terms t
where p.key = 'eb.secretary-general' and t.label = '2026-27'
on conflict do nothing;
